//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scriptngo.ConfigurationManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasSettingsUpgraded {
            get {
                return ((bool)(this["HasSettingsUpgraded"]));
            }
            set {
                this["HasSettingsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string SQLServerName {
            get {
                return ((string)(this["SQLServerName"]));
            }
            set {
                this["SQLServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SNG_CM")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string SQLServerUsername {
            get {
                return ((string)(this["SQLServerUsername"]));
            }
            set {
                this["SQLServerUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string SQLServerPassword {
            get {
                return ((string)(this["SQLServerPassword"]));
            }
            set {
                this["SQLServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SQLIntegratedSecurity {
            get {
                return ((bool)(this["SQLIntegratedSecurity"]));
            }
            set {
                this["SQLIntegratedSecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SQLServerNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SQLServerNames"]));
            }
            set {
                this["SQLServerNames"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BTP132237\\SQL;Initial Catalog=SNG_CM;Integrated Security=True")]
        public string PGTConnectionString {
            get {
                return ((string)(this["PGTConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cisco")]
        public string MRUVendor {
            get {
                return ((string)(this["MRUVendor"]));
            }
            set {
                this["MRUVendor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telnet")]
        public string MRUProtocol {
            get {
                return ((string)(this["MRUProtocol"]));
            }
            set {
                this["MRUProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUJumpServer {
            get {
                return ((string)(this["MRUJumpServer"]));
            }
            set {
                this["MRUJumpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigManager_Puller_CreateNewSet {
            get {
                return ((bool)(this["ConfigManager_Puller_CreateNewSet"]));
            }
            set {
                this["ConfigManager_Puller_CreateNewSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigManager_Puller_SeparateWindow {
            get {
                return ((bool)(this["ConfigManager_Puller_SeparateWindow"]));
            }
            set {
                this["ConfigManager_Puller_SeparateWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigManager_Puller_AutoSave {
            get {
                return ((bool)(this["ConfigManager_Puller_AutoSave"]));
            }
            set {
                this["ConfigManager_Puller_AutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal ConfigManager_Puller_HostPerForm {
            get {
                return ((decimal)(this["ConfigManager_Puller_HostPerForm"]));
            }
            set {
                this["ConfigManager_Puller_HostPerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal ConfigManager_Deployer_HostPerForm {
            get {
                return ((decimal)(this["ConfigManager_Deployer_HostPerForm"]));
            }
            set {
                this["ConfigManager_Deployer_HostPerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigManager_Deployer_SeparateForms {
            get {
                return ((bool)(this["ConfigManager_Deployer_SeparateForms"]));
            }
            set {
                this["ConfigManager_Deployer_SeparateForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfigManager_Deployer_StartScripts {
            get {
                return ((bool)(this["ConfigManager_Deployer_StartScripts"]));
            }
            set {
                this["ConfigManager_Deployer_StartScripts"] = value;
            }
        }
    }
}
